version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - asdf plugin add pixi
    - asdf install pixi latest
    - asdf global pixi latest
    - pixi run build-docs
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/_build/html/** $READTHEDOCS_OUTPUT/html/

sphinx:
    configuration: docs/conf.py