[project]
authors = [{name = "Jeffrey Larson"}, {name = "Stephen Hudson"},
            {name = "Stefan M. Wild"}, {name = "David Bindel"},
            {name = "John-Luke Navarro"}]

description = "libEnsemble community examples"
name = "libe-community-examples"
requires-python = ">= 3.9"
version = "0.1.0"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel", "pip>=24.3.1,<25", "setuptools>=75.1.0,<76", ]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64"]

[tool.pixi.pypi-dependencies]
libe_community_examples = { path = ".", editable = true }

[tool.pixi.environments]
default = []

[tool.pixi.dependencies]
python = ">=3.9,<3.14"
pip = ">=24.3.1,<25"