[project]
authors = ["jlnav <jnavarro@anl.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "libe-community-examples"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
clean = "rm -rf *.log *.txt, *.npy"

[dependencies]
python = "<=3.12"
libensemble = ">=1.4.3,<2"
black = ">=24.10.0,<25"
ipdb = ">=0.13.13,<0.14"

[pypi-dependencies]
torch = ">=2.5.1, <3"
torchvision = ">=0.20.1, <0.21"
