name: test-community-examples

on:
  workflow_dispatch:

    test-community-examples:

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        env:
            TERM: xterm-256color
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        defaults:
            run:
                shell: bash -l {0}

        steps:
        - uses: actions/checkout@v2
        - name: Setup conda
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: condaenv
            miniconda-version: "latest"
            python-version: 3.8
            channels: conda-forge
            channel-priority: flexible
            auto-update-conda: true

        - name: Force-update certifi, dependencies, install libEnsemble
          run: |
            python --version
            pip install -I --upgrade certifi
            pip install deap
            pip install scipy
            pip install libensemble

        - name: Install Ubuntu compilers
          run: conda install gcc_linux-64

        - name: Run tests
          run: |
            cd vtmop; python test_vtmop.py --comms local --nworkers 5
            cd ../deap; python test_deap_nsga2.py --comms local --nworkers 4
            cd ../consensus; python test_persistent_independent.py --comms local --nworkers 4
            python test_persistent_n_agent.py --comms local --nworkers 4
            python test_persistent_pds.py --comms local --nworkers 4
            python test_persistent_prox_slide.py --comms local --nworkers 4
